language: go
env:
  - TRAVIS="yes"
install:
  - go get github.com/shadowsocks/shadowsocks-go/shadowsocks
  - go get github.com/cyfdecyf/bufio
  - go get github.com/cyfdecyf/leakybuf
script:
  - cd $TRAVIS_BUILD_DIR
  - go test -v
  - ./script/test.sh
